# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: reveal-md CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      SOURCE_DIR: "./design.jskyzero.com"       # 源目录
      TARGET_DIR: "./output"                    # 目标目录
      FILE_NAME: "2023-11-13-ACT_with_GDC.md"   # 要查找的文件名

    steps:
    - name: 拉取工程
      uses: actions/checkout@v4

    - name: 拉取资产
      uses: actions/checkout@v4
      with:
        repository: 'jskyzero/design.jskyzero.com'
        path: ${{env.SOURCE_DIR}}
    - name: 处理文件
      run: ./move.sh

    - name: 设置 Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: 安装 reveal-md
      run: npm install -g reveal-md


    - name : Reveal-md Build
      # run: ./node_modules/.bin/reveal-md "$TARGET_DIR/$FILE_NAME" --assets-dir=assets --css theme.css --static _site
      run: reveal-md "$TARGET_DIR/$FILE_NAME" --static _site

    - name: 上传资产
      uses: actions/upload-pages-artifact@v3
      # with:
      #   path: "./_site" # Automatically uploads an artifact from the './_site' directory by default
    - name: 上传分支
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: "./_site"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
